import type { NextConfig } from "next";

// ---------------------------------------------------------------------------
// Content-Security-Policy
//
// Third-party surface:
//   • Clerk  — embedded auth UI, Cloudflare Turnstile bot protection, avatars
//   • Deepgram, AWS Bedrock, Stripe — server-side only; no browser allowance needed
//
// script-src uses 'unsafe-inline' because Clerk's embedded components inject
// inline scripts and Next.js emits small inline bootstrapping blocks.
// Migrate to a nonce-based policy in middleware once Clerk supports it cleanly.
//
// To tighten in production: set NEXT_PUBLIC_CLERK_DOMAIN to your custom Clerk
// host (e.g. "clerk.specscribe.com") so the wildcard is not needed.
// ---------------------------------------------------------------------------
const clerkHost =
  process.env.NEXT_PUBLIC_CLERK_DOMAIN ?? "*.clerk.accounts.dev";

const csp = [
  "default-src 'self'",
  // Next.js inline bootstrap + Clerk embedded UI require unsafe-inline.
  `script-src 'self' 'unsafe-inline' https://${clerkHost} https://challenges.cloudflare.com`,
  "style-src 'self' 'unsafe-inline'",
  // data: for QR-code images generated by the MFA setup route.
  // blob: for MediaRecorder audio blobs.
  `img-src 'self' data: blob: https://img.clerk.com`,
  // data: covers inlined woff2 from Next.js font optimisation.
  "font-src 'self' data:",
  // wss: allows Clerk's real-time session-sync WebSocket.
  `connect-src 'self' https://${clerkHost} wss://${clerkHost}`,
  // Clerk mounts its hosted UI in an iframe in certain flows.
  `frame-src https://${clerkHost}`,
  // Disallow this page being embedded anywhere (defence-in-depth with X-Frame-Options).
  "frame-ancestors 'none'",
  // Block Flash and other legacy plugins.
  "object-src 'none'",
  // Prevent <base> tag injection from hijacking relative URLs.
  "base-uri 'self'",
  // Only allow forms to POST to this origin.
  "form-action 'self'",
  "upgrade-insecure-requests",
].join("; ");

const nextConfig: NextConfig = {
  serverExternalPackages: ["@prisma/client", "bcryptjs"],
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "img.clerk.com" },
    ],
  },
  headers: async () => [
    {
      source: "/(.*)",
      headers: [
        { key: "Content-Security-Policy", value: csp },
        { key: "X-Content-Type-Options", value: "nosniff" },
        // Kept alongside frame-ancestors for browsers that pre-date CSP level 2.
        { key: "X-Frame-Options", value: "DENY" },
        { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
        {
          key: "Permissions-Policy",
          value: "camera=(), microphone=(self), geolocation=(), payment=()",
        },
        {
          key: "Strict-Transport-Security",
          value: "max-age=63072000; includeSubDomains; preload",
        },
      ],
    },
  ],
};

export default nextConfig;
